name: Check if deployment works
run-name: testing
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Copy changed files to server
      uses: appleboy/ssh-action@v1
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        port: 22
        script: |
                cd deptst/deptst
                python main.py